### ISSUE TITLE
Cleanup search index when a namespace is deleted.

### ISSUE THREAD

**Issue by tamalsaha** [appscode/kubed#109]

**Comment by a8uhnf** [comment]
Delete namespace cleanup search index, under that specific namespace

example:
create a namespace
$ kubectl create namespace development

---

Create a deployment with below yaml

```
apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: development
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```
---

Then search `/search?q=development` gives search result associates with word development. 
After delete development namespace `/search?q=development` show empty search result
