### ISSUE TITLE
Rethink copying config/secret to kube-public namespace

### ISSUE THREAD

**Issue by tamalsaha** [appscode/kubed#113]
https://github.com/kubernetes/kubeadm/issues/320
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: kube-public
  name: 'system:bootstrap-signer-clusterinfo'
rules:
- apiGroups: [""]
  resources: ["configmap"]
  resourceNames: ["cluster-info"]
  verbs: ["get"]
```

http://blog.kubernetes.io/2017/01/stronger-foundation-for-creating-and-managing-kubernetes-clusters.html
