### ISSUE TITLE
secrets syncing is not proper

### ISSUE THREAD

**Issue by r-divakaran** [appscode/kubed#233]
Hello,

I was trying to set up kubed, for a cluster. Installed using helm as below
```
helm install stable/kubed --name kubed 
```

Then created a secret, using below file
```
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
  annotations:
    kubed.appscode.com/sync: ""
data:
  .dockerconfigjson: xxxxxxxxxxxxxxxxxxx-====---=xkjxxcoxox--==
type: kubernetes.io/dockerconfigjson
```

Once the secret is created am trying to install one of our service using helm in another namespace called kube-p, but its not working as its not able to download the docker image from our registry. As the above secret is supposed to be used.
One thing I noticed is that the secret I created is of type kubernetes.io/dockerconfigjson, but when they are synced by kubed to other namespaces they are of type opaque.
```
default        image-pull-secret                  kubernetes.io/dockerconfigjson        1         1m
kube-x   image-pull-secret                  Opaque                                1         1m
kube-y    image-pull-secret                  Opaque                                1         1m
kube-system    image-pull-secret                  Opaque                                1         1m
kube-z     image-pull-secret                  Opaque                                1         1m
kube-p        image-pull-secret                  Opaque                                1         1m
```
Is that an expected behaviour !? 

I am suspecting its an issue with kubed coz, when I create the secret without appscode annotation separately to each namespace, things are working as expected. 

Thanks,
Raju
