### ISSUE TITLE
Context not found in kubeconfig file

### ISSUE THREAD

**Issue by jd0x** [appscode/kubed#389]
I have Kubed installed using the most recent Helm 3 chart. The cluster synchronization feature is working great, however, the pod logs are throwing errors stating the cluster context is not found. The feature is working as expected, so it seems to be a false positive. 

I provided the log and an example schema of the kubeconfig being used.

Log error
``` bash
E0404 21:53:55.119680 1 resourcehandlers.go:99] context <MY_CLUSTER_CONTEXT> not found in kubeconfig file
```

Kubeconfig
``` yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <REDACTED>
    server: <REDACTED>
    name: my-cluster
contexts:
- context:
    cluster: my-cluster
    user: my-cluster-admin
  name: my-cluster
```
Kubernetes version: 1.15.9
Kubed version: kubed:v0.12.0-rc.2

P.S. Thank you for open-sourcing this super useful package 😄
